// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var DiffieHellman = require("diffie-hellman");

function prime_encodingToJs(enc) {
  if (enc !== -714733139) {
    if (enc >= 5194459) {
      return "hex";
    } else {
      return "base64";
    }
  } else {
    return "latin1";
  }
}

function prime_encodingToJs_rev(enc) {
  return "hex";
}

function createDiffieHellman1(prime_length) {
  return DiffieHellman.createDiffieHellman(prime_length);
}

function createDiffieHellman4(prime, prime_encoding, generator, generator_encoding) {
  return DiffieHellman.createDiffieHellman(prime, prime_encodingToJs(prime_encoding), generator, prime_encodingToJs(generator_encoding));
}

function getGenerator(instance, prime_encoding) {
  return instance.getGenerator(prime_encodingToJs(prime_encoding));
}

function getPrime(inst, prime_encoding) {
  return inst.getPrime(prime_encodingToJs(prime_encoding));
}

function generateKeys(inst, prime_encoding) {
  var enc = prime_encodingToJs(prime_encoding);
  return inst.generateKeys(enc);
}

function getPrivateKey(inst, prime_encoding) {
  return inst.getPrivateKey(prime_encodingToJs(prime_encoding));
}

function getPublicKey(inst, prime_encoding) {
  return inst.getPublicKey(prime_encodingToJs(prime_encoding));
}

function computeSecret(inst, other_public, input_encoding, output_encoding) {
  return inst.computeSecret(other_public, prime_encodingToJs(input_encoding), prime_encodingToJs(output_encoding));
}

exports.prime_encodingToJs = prime_encodingToJs;
exports.prime_encodingToJs_rev = prime_encodingToJs_rev;
exports.createDiffieHellman1 = createDiffieHellman1;
exports.createDiffieHellman4 = createDiffieHellman4;
exports.getGenerator = getGenerator;
exports.getPrime = getPrime;
exports.generateKeys = generateKeys;
exports.getPrivateKey = getPrivateKey;
exports.getPublicKey = getPublicKey;
exports.computeSecret = computeSecret;
/* diffie-hellman Not a pure module */
